### ISSUE TITLE
Please include tests in the pypi tarball

### ISSUE THREAD

**Issue by mgorny** [hukkin/tomli#114]
On Gentoo we really want to let our users run tests before installing the package. Normally, we just use the autogenerated GitHub archives for that. However, since tomli uses `pyproject.toml`, this will effectively create a cyclic dependency between flit and itself once flit switches over from toml (and it already creates one for the Gentoo build tool).

Could you please include the necessary test files in the generated pypi tarballs? Since they include a backwards compatible `setup.py` script, they would really help us avoid cyclic dependencies.

**Comment by hukkin** [comment]
Understood, I can add tests in the next release if there's no better solution. However, would it be better if Flit vendored Tomli instead? Otherwise we're relying on the "backwards compatible setup.py script" that you mentioned. I wouldn't be surprised if build tools no longer include it in PEP 517 source distributions some day in the future.

**Comment by hukkin** [comment]
Maybe @takluyver as flit maintainer and packaging expert knows best?

**Comment by mgorny** [comment]
pyproject2setuppy is the tool we're using, and I really don't want to vendor anything.

**Comment by hukkin** [comment]
:+1:

Just out of curiosity: why convert to setup.py at all instead of using the PEP517 native [build](https://github.com/pypa/build)? Is it because `build` has dependencies (and again cyclic ones)? If `build` vendored dependencies, would it be usable?

**Comment by takluyver** [comment]
I have aimed to make Flit bootstrappable: `flit_core` should be able to build itself with [no dependencies](https://github.com/takluyver/flit/blob/8d9af11e8920f81d5a9f581e82eb5dd80d0371b4/flit_core/pyproject.toml#L2) - it requires a toml parser at runtime, but not to build. You can then use `flit_core` to package tomli - once we switch to using tomli, you'll need to arrange for it to import the source copy of tomli which is about to be packaged. And then those two pieces should be sufficient to build other Flit-packaged projects, including the `flit` command line package.

The bootstrapping probably has to be something of a special case for downstream packagers: you have to build `flit_core` before its runtime dependency, and skip running its tests and packaging `flit` until a later point. But I don't see any good way to avoid that, until/unless a TOML parser is one day part of the Python standard library.

**Comment by mgorny** [comment]
Long story short, it is primarily because PEP517 is useless outside the narrow case of building wheels, i.e. when you actually need these files unpacked. I mean, we could technically build wheels and then unpack them back but that sounds like a serious waste of resources.

**Comment by mgorny** [comment]
That said, I've noticed that the flit-generated `setup.py` is using pure distutils, and I've been able to resolve this by adding a two-liner `setup.py` to our ebuild, so feel free to close this.

**Comment by takluyver** [comment]
> we could technically build wheels and then unpack them back but that sounds like a serious waste of resources.

That is essentially how Python packaging is meant to work now. Build tools produce wheels as the standard way to specify "this is what should get installed", and we're aiming for a world where all installed packages have been in a wheel at some point (even if that's a temporary wheel on the installing machine).

There was discussion at some point of having an 'unpacked wheel' option, with the wheel contents as a directory of files rather than packed into a zip file. That could save packing and extracting wheels. But some backends wanted to carefully control how the zip file was built (for reproducibility), and the benefits didn't seem worth the added complexity, so it was left out. For most small packages, creating and unpacking a zip file is very quick anyway. But this proposal could always be revisited if you were interested in pushing for it.

**Comment by mgorny** [comment]
I'm sorry but I can't really afford to push for it. I'm completely overwhelmed with work, and every month something new falls on me.

**Comment by jmroot** [comment]
We're also having trouble with circular dependencies in MacPorts, specifically the `pep517` module being required for PEP 517-style builds and also depending on `tomli`. We dropped in the `setup.py` from the previous version to solve the problem for now, but that doesn't seem sustainable.

**Comment by hukkin** [comment]
@jmroot would something similar work for you that [Gentoo did](https://github.com/gentoo-mirror/gentoo/commit/363c9acaad279261010253c3fe3b58b871d95a96), i.e. adding a two-liner setup.py? Arch linux seems to use dephell to [autogenerate](https://github.com/archlinux/svntogit-packages/blob/48e0d4a50685f82fec00f65a2f5ea9621eb7213d/trunk/PKGBUILD) a similar file.

I could also keep adding the setup.py in sdist if you _really_ need it, but don't think that's sustainable either as it's __a)__ not using PEP517 and __b)__ the legacy setup.py creation feature will eventually be removed from all build tools.

My understanding (based on e.g. takluyver's input above) is that the sustainable way here is to build `tomli` and `pep517` using a source copy of `tomli`. It seems like a stdlib TOML parser would really simplify things here though...

**Comment by jmroot** [comment]
The reason using a setup.py is helpful here is because setuptools vendors its dependencies in order to avoid these kinds of bootstrap problems. I think that the PEP 517 front ends mostly likely need to do the same to make them practical for distro use. For now, doing a PEP 517 build of anything that is itself required to do a PEP 517 build is a problem, so we avoid doing it.

I definitely agree that a TOML parser should be in the stdlib given that it is needed for the officially supported build interface; in fact there should be a complete basic front end in the stdlib. But even that won't completely solve the problem for many years yet, until the last python version that doesn't include those modules is EOL.

**Comment by mgorny** [comment]
Normally I'd say it would be even simpler for distros not to use any setup tool and just install the directory straight to the filesystem. However, this wouldn't include egg-info, and therefore requirements would be broken.

> I definitely agree that a TOML parser should be in the stdlib given that it is needed for the officially supported build interface; in fact there should be a complete basic front end in the stdlib. But even that won't completely solve the problem for many years yet, until the last python version that doesn't include those modules is EOL.

I've requested that in the past: https://bugs.python.org/issue40059. However, it didn't make it to Python 3.10, so the problem is going to stay even longer now.

**Comment by mgorny** [comment]
And now setuptools started requiring tomli via `pkg_resources`, so it's no longer possible to bootstrap tomli via `setup.py`.

**Comment by mgorny** [comment]
Oh, I'm sorry, the sdist tarball doesn't include egg-info anyway, so it's of no help. I'm going to close the bug now since there's no real gain from including the tests anymore.
