### ISSUE TITLE
Custom `datetime` parsers?

### ISSUE THREAD

**Issue by oittaa** [hukkin/tomli#150]
`datetime` in standard library has a microsecond precision, but for example `numpy.datetime64` has a nanosecond precision. It would be pretty easy to add another parameter `parse_datetime` like the current `parse_float`. Even something a bit more complex like the custom JSON [encoders and decoders](https://docs.python.org/3/library/json.html#json.JSONDecoder) might be useful. Or do you think custom parsers would complicate things too much?

**Comment by hukkin** [comment]
Hey, thanks for the issue!

I'd rather not add any parameters simply because they are easy to add or may potentially be useful. I'd prefer to only consider if there's a real world use case that benefits somebody. Do you have a need for nanosecond precision? And if you do, as first option I'd still first consider using a TOML string and parsing the datetime yourself, because TOML spec gives no guarantees of anything more than millisecond precision, so even if this parser preserves the the extra decimals, another parser probably doesn't. Your TOML will not portable.
