### ISSUE TITLE
Python 3.6 is not supported anymore

### ISSUE THREAD

**Issue by pombredanne** [hukkin/tomli#194]
The doc states:
```
To build code that uses the standard library if available, but still works seamlessly with Python 3.6+, do the following.
```
but you bumped requirements to Python 3.7+ in https://github.com/hukkin/tomli/commit/6a93a19f4996f01f670d67d5fc0ff90b65a69234

I wished this could still run on Python 3.6 as advertized which is still supported on many Linux distros.

**Comment by hukkin** [comment]
Tomli 2.0.0+ doesn't support Python 3.6, but versions 1.x do. Version 1.2.3 still works flawlessly together with Python 3.6. Any well-behaved installer (e.g. modern pip versions) will install it instead of a 2.x release if you're running Python 3.6.

I'm not aware of any bugs in version 1.2.3 and don't see the existence of 2.x releases as a blocker for using it.

**Comment by pombredanne** [comment]
@hukkin Thanks! So you just need to update the README to clarify this I guess?

**Comment by pombredanne** [comment]
Sorry ... I missed your point. I get it now. Thanks!
