### ISSUE TITLE
Type stub incompatiblity with tarfile.ExFileObject (i.e. tarfile.TarFile.extractfile() result)

### ISSUE THREAD

**Issue by mgorny** [hukkin/tomli#214]
Please consider the following snippet:

```python
import tomli
import tarfile

with tarfile.open("test.tar") as tar:
    f = tar.extractfile("test.toml")
    assert f is not None
    tomli.load(f)
```

When I run mypy on it, I get:

```
test.py:7: error: Argument 1 to "load" has incompatible type "IO[bytes]"; expected "BinaryIO"  [arg-type]
Found 1 error in 1 file (checked 1 source file)
```

To be honest, [typing docs](https://docs.python.org/3/library/typing.html#typing.IO) don't really say what the difference between `IO[bytes]` and `BinaryIO` is. Besides type stubs, the code works. FWICS, tomllib would suffer from the same problem if not for the fact that [mypy overrides its type stub](https://github.com/python/mypy/blob/756277c8bbab01dab0833c7f18d3f2765211352b/mypy/typeshed/stdlib/tomllib.pyi) to:

```python
def load(__fp: SupportsRead[bytes], *, parse_float: Callable[[str], Any] = ...) -> dict[str, Any]: ...
```

**Comment by hauntsaninja** [comment]
I think using something like `SupportsRead[bytes]` might end up being the most user friendly thing.

I think BinaryIO should be avoided. There's not really any difference between it and IO[bytes] and it mainly just serves to confuse. In general, typeshed tries to avoid use of BinaryIO and TextIO, and even of IO. These things were added to the stdlib before protocols were a thing. In practice they often don't work well because it turns out there's a tonne of variation in what "file-like" actually means, and they don't capture well the difference between readers and writers. There's more discussion at https://github.com/python/typing/discussions/829

**Comment by mgorny** [comment]
Thanks for the fix. Would you also submit it to `tomllib` or should I try?

**Comment by hauntsaninja** [comment]
We don't need to change tomllib, since nothing looks at type hints in the standard library; everything just looks at typeshed

**Comment by hukkin** [comment]
Yup, and typeshed [already uses SupportsRead](https://github.com/python/typeshed/blob/main/stdlib/tomllib.pyi) so you shouldn't have this issue with `tomllib`.

**Comment by mgorny** [comment]
> We don't need to change tomllib, since nothing looks at type hints in the standard library; everything just looks at typeshed

Well, *I* did look at types in the stdlib at first and took me quite a while to figure out why mypy complains about tomli and not the "identical" types in tomllib.
