### ISSUE TITLE
Why splitting the library into two?

### ISSUE THREAD

**Issue by Yura52** [hukkin/tomli#81]
Hi! I like the idea of having a simple pure Python library for TOML! And I understand the motivation of keeping it minimal, however, I am not sure if splitting the package into two is the optimal approach. I would like to share my thoughts on that.

1. If I am a user that does NOT need  `dump(s)`, what is the benefit of NOT having `dump(s)`? By looking at tomli-w, it seems that the benefit is the absence of ~150 lines of Python code. If it is true, I personally do not see use cases where this benefit can be important. I understand the goal of "theoretically minimal library". Are you sure that this goal is practical?
2. If I am a user that needs  `dump(s)`, I have to install two packages instead of one and import two different packages instead of one. This setup does not feel minimal to me (unfortunately, this is exactly my case).
3. In fact, tomli is not minimal: `loads` can be replaced by using `StringIO` and `load` :) While this is rather a joke, I would like to say that the "minimalism", when not absolute, becomes a subjective thing.

Taking all this into account, merging the two libraries into one looks good to me. What do you think?

**Comment by Yura52** [comment]
An alternative solution could be three libraries: tomli-r, tomli-w and tomli, where the latter one wraps the -r and -w versions.

**Comment by hukkin** [comment]
Hey there, thanks for the discussion starter!

The answer to most of your questions is something along the lines of "yeah, it's subjective" or "I don't know" :smile: I'm still not sure how the setup will look like in say 1 year from now. The options I've had in mind are:
- The current state with two packages: one for reading and one for writing
- Moving write capability to Tomli so that there's only one package
- Tomli-W stays separate but usable as a plugin of sorts: `pip install tomli[dumps]` will install Tomli-W and inject `dumps` and `dump` to `tomli` namespace

I think much depends on feedback from others (just like what you did here, thanks for that).

> what is the benefit of NOT having dump(s)

For a user: the absence of ~150 LOC as you mentioned. For me (the maintainer): the ability to break one package without breaking the other. A theoretical example: if I decide to expand Tomli-W with style editing capabilities and the API grows, I may want to make breaking changes eventually, and don't want that to have an effect on Tomli the read-only package. Especially right now that I'm unsure, the current state gives me the most freedom as a maintainer.

> I personally do not see use cases where this benefit can be important

This could be valuable for projects like `pip` that will be installed in even the most peculiar and resource constrained places. Also size-optimized Docker images, etc... I may also be wrong here.

> Are you sure that this goal is practical?

No. :smile: 

> If I am a user that needs dump(s) ... This setup does not feel minimal to me

Yeah I can see that. Still, `pip install tomli tomli-w` instead of `pip install tomli` shouldn't be the end of the world, or?

> Taking all this into account, merging the two libraries into one looks good to me. What do you think?

Yeah I'm not totally against it, but as you can probably tell by now, I don't know what the best way is, so as for now, easiest is to not change anything.

> An alternative solution could be three libraries: tomli-r, tomli-w and tomli, where the latter one wraps the -r and -w versions.

I'd personally favor the `tomli[dumps]` install extra approach instead of this, if I go down that road.

----

One more thing I'd like to say is that my understanding is that write use cases are far fewer than read-only use cases, so you, having to install both packages, may be in the minority. I could be wrong. Also I feel like most write use cases benefit from style preservation, so Tomli-W may not be as valuable as the style-preserving `tomlkit`. These are further reasons why write capability started off as its own package.

**Comment by Yura52** [comment]
@hukkin thanks for the detailed answer!

> shouldn't be the end of the world
> ...
> so you, having to install both packages, may be in the minority

As for `pip install`, it is not a problem at all; the main inconvenience comes from two imports and two modules `tomli` and `tomli_w` instead of one.

The solution `tomli[dumps]` looks good!

**Comment by takluyver** [comment]
Just to add another possible reason for keeping them separate: some of us hope to one day have a TOML parser in the Python standard library. Given all the possible choices involved in writing TOML, it's conceivable that a parser-only implementation has a better chance of being adopted than one that has both reading and writing.

Of course, even if that's true, it's a fairly minor point, because the parsing parts could always be split off again to join the standard library. But if there's a stable, widely-used parser-only library ready, it would be easier to adopt. And having separate install statistics for the parser and writer might help inform the decision.

**Comment by 4A47** [comment]
The main tomli package should have read and write by default, anything else would be bizarre. The fact that they are not together would lead me to look for a different package that has both. You can still keep good separation inside the package or maintaining.

**Comment by hukkin** [comment]
> The main tomli package should have read and write by default, anything else would be bizarre. The fact that they are not together would lead me to look for a different package that has both.

Not all things bizarre are necessarily bad. :wink:   If you need a package that has both read and write, I can recommend [TOML Kit](https://github.com/sdispater/tomlkit).

> You can still keep good separation inside the package for maintaining.

You've misunderstood my concern. I was never worried about code separation. In fact, having both in the same package actually removes some maintenance burden. But it puts read and write functionality under shared package and version number, that was my concern.

---

Now that Tomli will be integrated to the standard library (PEP 680), I think I'll keep Tomli and Tomli-W separate at least as long as Tomli serves as a stdlib backport (approximately October 2026, i.e. Python 3.10 EOL date). An exception being if Tomli-W is added to stdlib too, but I'd be very surprised if that happens.
