### ISSUE TITLE
Support reading TOML from a filename.

### ISSUE THREAD

**Issue by domdfcoding** [hukkin/tomli#99]
Both [uiri/toml](https://github.com/uiri/toml) and [samuelcolvin/rtoml](https://github.com/samuelcolvin/rtoml) support filenames in their `load` functions. They are then responsible for opening the file with the correct encoding and reading its contents, before calling `loads`.

However, `tomli` only supports file-like objects, leaving it to the user to open the file and, inevitably, forgetting to use UTF-8 as the encoding (e.g. https://github.com/pulls?q=is%3Apr+author%3Adomdfcoding+UTF-8).

I propose copying `toml` and `rtoml` and adding support for strings and `os.PathLike` objects. That way the user can write:

```python
config = tomli.load("pyproject.toml")
```

or 

```python
config = tomli.load(pathlib.Path("pyproject.toml"))
```

without having to worry about the encoding, and saving a line over the `with open` approach.

-----

What do you think? If you're happy with the idea I'll submit a PR

**Comment by hukkin** [comment]
Heyy, thanks for the issue!

My initial reaction was a strict "no thanks" :smile: That's because the following code has confused me more than once
```python
import toml
f = "path/config.toml"
toml.load(f)
```
It's confusing because it behaves unlike `load` methods of the stdlib, so every time I see it my first thought is "that's a bug". And when I realize it's not, it still makes the code less obvious about what types are used, hence, at least for me, less readable. I also dislike providing many ways to do one thing.

That said, TOML is special in the way that you mentioned, that it's not just a data serialization format, but a file format that requires UTF-8 encoding. So I agree that providing API that abstracts encoding away from the user would be kind of nice. Maybe that should be `tomli.load_path` instead though, for reasons explained above?

I'll have to think about this. Right now I'm leaning towards not providing many ways to do one thing. Also, with `pathlib` the code
```python
tomli.loads(path.read_text("utf-8"))
```
isn't too verbose and is crystal clear of what's going on.

**Comment by hukkin** [comment]
An added note: In `rtoml` the following code:
```python
rtoml.load("path/config.toml")
```
seems to parse the string value "path/config.toml" instead of the content of a file with that name. This is also the kind of confusion that I'd like to have no part in.

**Comment by Yura52** [comment]
Overall, I think it is a good idea to provide a shortcut for what is probably the most popular use case. Having `loads` without having a function for loading file by path looks somewhat strange to me, because TOML is a configuration language and loading a *configuration file* is likely to be a more popular scenario than loading a string.

As for naming, `loadp` can be also considered as a counterpart of `loads`, but for **p**aths.

> In `rtoml`

I totally agree that the design of `rtoml.load` is confusing: you must do `from pathlib import Path` and pass Path objects to `rtoml.load` to make it work.

> ```python
> tomli.loads(path.read_text("utf-8"))
> ```
> isn't too verbose

Unfortunately, in practice, it is not just this line: you also have to add `from pathlib import Path` and wrap your string object into `Path`.

**Comment by layday** [comment]
The stdlib `json` module skirts around this issue by accepting `bytes` and `bytearray` as input to `loads`, so you can open the file in binary mode and let `json` do the decoding.

**Comment by hukkin** [comment]
@layday Yeah I'm starting to think `open("conf.toml", "rb")` is the way to go here, as I realized the lack of utf-8 encoding [isn't the only issue with text-based file objects](https://github.com/toml-lang/toml/issues/837): users should also disable universal newlines with `open("conf.toml", encoding="utf8", newline="")`.

Text-based file objects seem like enough of a footgun that I'm considering a possible deprecation/warning/removal in favor of binary file objects.

**Comment by hukkin** [comment]
Support for binary file objects was added in v1.1.0 and support for text file objects will be deprecated in an upcoming v1.2.0. I'm hoping these changes are sufficient to discourage non-UTF-8 decoding and use of universal newlines, and also resolve this issue.

**Comment by Yura52** [comment]
@hukkin thanks for the improvement! If I understand correctly, the commit mentioned above only deprecates text streams as input, but does not add the ability to load TOML using paths. Do you plan to add this feature? I mean things like:
- (I personally vote for this) making `load` accept Path-like objects (including strings)
- adding a new function such as `loadp` or `load_path`

**Comment by hukkin** [comment]
> If I understand correctly, the commit mentioned above only deprecates text streams as input, but does not add the ability to load TOML using paths

This is correct.

> Do you plan to add this feature?

I don't currently feel like pathlib specific API additions are necessary. Pathlib Paths are supported by the `open` builtin, so the following works already:

```python
import tomli
from pathlib import Path

p = Path("foo.toml")

with open(p, "rb") as f:
    tomli.load(f)

# ... or an alternative pathlib specific way
with p.open("rb") as f:
    tomli.load(f)


# ... or a one-liner
tomli.loads(p.read_bytes().decode())
```

If the standard library decides to add pathlib support to the various `load` funcs (in `json`, `pickle` and `marshal` modules) then I will copy that behavior though.

**Comment by Yura52** [comment]
> standard library

By the way, [json.loads](https://docs.python.org/3/library/json.html#json.loads) accepts not only `str`, but also `bytes` and `bytearray` (no need for `.decode()` in the last snippet).

**Comment by graingert** [comment]
> If the standard library decides to add pathlib support to the various load funcs (in json, pickle and marshal modules) then I will copy that behavior though.

there's movement to support this in json.loadp

**Comment by Yura52** [comment]
> > If the standard library decides to add pathlib support to the various load funcs (in json, pickle and marshal modules) then I will copy that behavior though.
> 
> there's movement to support this in json.loadp

The following discussion is relevant:
https://discuss.python.org/t/vote-new-function-for-reading-json-from-path/7603

Well, my impression after reading is that the chance of adding `json.load_path` is close to zero :)

**Comment by graingert** [comment]
`tomli.loads(path.read_text("utf-8"))` doesn't work correctly right? you need to use:


```python
with path.open(encoding="utf8", newline="") as f:
    tomli.load(f)
```

**Comment by hukkin** [comment]
@graingert All three examples listed here https://github.com/hukkin/tomli/issues/99#issuecomment-889422956 work equally well. And so does your second example. Your first example (`tomli.loads(path.read_text("utf-8"))`) will not raise an error if CR line endings are used, even though that is invalid TOML.

**Comment by graingert** [comment]
@hukkin I've made "read-toml" for minimal pain toml reading: https://github.com/graingert/read-toml/blob/default/read_toml/_impl.py#L23
